name: size
on: [pull_request]
jobs:
  size:
    runs-on: ubuntu-latest

    # skipping for now
    if: ${{ false }}

    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1

      # https://github.com/andresz1/size-limit-action
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # build_script (optional custom npm script)
          # skip_step (optionally skip 'install' or 'build')
          # directory (optional custom working directory)
